### ISSUE TITLE
Error in getobjP(objNull$Cova, yMat, muMat, iRMat) : Not a matrix.`

### ISSUE THREAD

**Issue by egyanar** [WenjianBI/POLMM#1]
Hello. When I run the package I get the following error. In addition `objNull = POLMM::POLMM_Null_Model(as.factor(y2)~Q1+Q2, 
                           data=egData, PlinkFile = PlinkFile, subjData = egData$Taxa)
` does calculate yMat, muMat as NaN. 

![image](https://user-images.githubusercontent.com/37454187/126908797-3ab615bf-3166-4282-91f1-d5f9d8afc403.png)

`> POLMM::POLMM.plink(
+   objNull=objNull,
+   PlinkFile=PlinkFile,
+   output.file="outFile.txt",
+   chrVec.plink = names(objNull$LOCOList),
+   )
[1] "Totally 7530 markers in plink files."
[1] "After filtering by 'chrVec.plink', 7530 markers are left."
[1] "Split all markers into 1 chunks."
[1] "Each chunk includes less than 11627906 markers."
[1] "Analyzing chunk 1/1."
start
file = C:/Users/Corbeau/Desktop/POLMM/geno
Sun Jul 25 20:51:38 2021 - read bim
Sun Jul 25 20:51:38 2021 - read fam
extract 7530 marker and 86 sample out of 7530 marker and 86 sample
Sun Jul 25 20:51:38 2021 - read bed
Binary PLINK BED file is ready to read
build a look-up table
assigned 647580 values 
allocate dim and dimnames
Sun Jul 25 20:51:38 2021 - end
Totally 7530 markers to analyze!!
Error in getobjP(objNull$Cova, yMat, muMat, iRMat) : Not a matrix.`

**Comment by WenjianBI** [comment]
We have put POLMM approaches to a new R package GRAB, of which the documentation is https://wenjianbi.github.io/grab.github.io/. I am wondering if you can try that package?
