### ISSUE TITLE
Using a family relatedness matrix instead of sparse GRM?

### ISSUE THREAD

**Issue by hmkweon** [WenjianBI/POLMM#2]
Hello,

Thanks for this great tool. I am just wondering if you have considered to use a family relatedness matrix as in fastGWA or have done any simulation. We won't be able to use LOCO, but we won't have to compute a GRM. It would be great to know how different results are if we use a family relatedness matrix.

Best wishes,
Hermon

**Comment by WenjianBI** [comment]
We have moved this approach to GRAB package, of which the documentation is https://wenjianbi.github.io/grab.github.io/.

Thanks for the question. We did not conduct the related evaluation but I think the analysis should be OK. You can also make a "sparse GRM" using the kinship coefficient estimated from family relationship. 

Thanks,
Wenjian
