### ISSUE TITLE
non-human chromosomes

### ISSUE THREAD

**Issue by erikenbody** [WenjianBI/POLMM#3]
Hi there, 

Is there a workaround to run getSparseGRMParallel with non-human chromosome numbering? When passing a plink bfile, I receive the following error:

```
Error: Line 18980 of [autosomes_pruned.bim] contains illegal chr number, please check
```

This is because plink doesn't like non-human chromosome names such as chr27+. I can run it just fine by excluded chromosomes with non-overlapping names.

Otherwise do you have a workaround? I recognize this is in part an issue with gcta, but it could possibly be solved by allowing bgen files in getSparseGRMParallel.

Thanks!

**Comment by WenjianBI** [comment]
We have moved this approach to GRAB package, of which the documentation is https://wenjianbi.github.io/grab.github.io/.

Thanks for the question. The main code to calculate sparse GRM is from GCTA. I think allowing bgen file in getSparseGRMParallel is not top priority. The main advance of bgen format (compared to plink format) is that it supports imputation data. When calculating sparse GRM, we recommend using high quality genotype data and plink file maybe is better.

To be honest, I am not familiar about non-human genome analysis. I think you might be very careful to use tools developed for human genome analysis. You can feel free to contact me via wenjianb@pku.edu.cn.

Thanks,
Wenjian
